branch-defaults:
  master:
    environment: schonberg-lab01-dev
    group_suffix: null
global:
  application_name: schonberg-lab01
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: eu-west-1
  profile: eb-cli
  sc: git
